// src/components/properties/index.ts
export { default as TextPropertiesPanel } from './TextPropertiesPanel'
export { default as ShapePropertiesPanel } from './ShapePropertiesPanel'
export { default as ImagePropertiesPanel } from './ImagePropertiesPanel'
export { default as BlurbPropertiesPanel } from './BlurbPropertiesPanel'
export { default as LinePropertiesPanel } from './LinePropertiesPanel'
export { default as IconPropertiesPanel } from './IconPropertiesPanel'
export { default as TablePropertiesPanel } from './TablePropertiesPanel'
export { default as CircularTailSelector } from './CircularTailSelector'
export { default as BlendModeSelector } from './BlendModeSelector'
export { default as EffectsControls } from './EffectsControls'
